back_office_user:
    resource: "@BackOfficeUserBundle/Resources/config/routing.yml"
    prefix:   /usermanagement

back_office_school:
    resource: "@BackOfficeSchoolBundle/Resources/config/routing.yml"
    prefix:   /
    
test_api:
    type:     rest
    prefix:   /api
    resource: "@BackOfficeSchoolBundle/Resources/config/api-routing.yml"
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"