back_office_user:
    resource: "@BackOfficeUserBundle/Resources/config/routing.yml"
    prefix:   /

back_office_school:
    resource: "@BackOfficeSchoolBundle/Resources/config/routing.yml"
    prefix:   /
