eleve:
    path:     /
    defaults: { _controller: BackOfficeSchoolBundle:Eleve:index}
eleve_add:
    path:     /add
    defaults: { _controller: "BackOfficeSchoolBundle:Eleve:add" }
eleve_json_result:
    pattern:  /json
    defaults: { _controller: "BackOfficeSchoolBundle:Eleve:Json" }
    options:
        expose: true
