parameters:
#    back_dash.example.class: Back\DashBundle\Example

services:
#    back_dash.example:
#        class: %back_dash.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    page_load_listener:
        class: BackOffice\UserBundle\Listener\SecurityListener
        arguments: [@templating,@router, @security.context]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
        security.exception_listener.class: BackOffice\UserBundle\Security\Firewall\ExceptionListener