<?php

namespace BackOffice\SchoolBundle\Document;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * EleveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EleveRepository extends DocumentRepository
{
}